// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_service.proto

package zros_example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestServiceRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestServiceRequest) Reset()         { *m = TestServiceRequest{} }
func (m *TestServiceRequest) String() string { return proto.CompactTextString(m) }
func (*TestServiceRequest) ProtoMessage()    {}
func (*TestServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_service_dd52fe580bf3ab18, []int{0}
}
func (m *TestServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestServiceRequest.Unmarshal(m, b)
}
func (m *TestServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestServiceRequest.Marshal(b, m, deterministic)
}
func (dst *TestServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestServiceRequest.Merge(dst, src)
}
func (m *TestServiceRequest) XXX_Size() int {
	return xxx_messageInfo_TestServiceRequest.Size(m)
}
func (m *TestServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestServiceRequest proto.InternalMessageInfo

func (m *TestServiceRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TestServiceRequest) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type TestServiceResponse struct {
	Detail               string   `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestServiceResponse) Reset()         { *m = TestServiceResponse{} }
func (m *TestServiceResponse) String() string { return proto.CompactTextString(m) }
func (*TestServiceResponse) ProtoMessage()    {}
func (*TestServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_service_dd52fe580bf3ab18, []int{1}
}
func (m *TestServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestServiceResponse.Unmarshal(m, b)
}
func (m *TestServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestServiceResponse.Marshal(b, m, deterministic)
}
func (dst *TestServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestServiceResponse.Merge(dst, src)
}
func (m *TestServiceResponse) XXX_Size() int {
	return xxx_messageInfo_TestServiceResponse.Size(m)
}
func (m *TestServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestServiceResponse proto.InternalMessageInfo

func (m *TestServiceResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*TestServiceRequest)(nil), "zros_example.TestServiceRequest")
	proto.RegisterType((*TestServiceResponse)(nil), "zros_example.TestServiceResponse")
}

func init() { proto.RegisterFile("test_service.proto", fileDescriptor_test_service_dd52fe580bf3ab18) }

var fileDescriptor_test_service_dd52fe580bf3ab18 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x49, 0x2d, 0x2e,
	0x89, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xa9, 0x2a, 0xca, 0x2f, 0x8e, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55, 0x72, 0xe2, 0x12,
	0x0a, 0x49, 0x2d, 0x2e, 0x09, 0x86, 0x28, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe1, 0x62, 0x4d, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70,
	0x84, 0xc4, 0xb8, 0xd8, 0x52, 0x52, 0x4b, 0x12, 0x33, 0x73, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38,
	0x83, 0xa0, 0x3c, 0x25, 0x5d, 0x2e, 0x61, 0x14, 0x33, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x91,
	0x94, 0x33, 0x22, 0x2b, 0x4f, 0x62, 0x03, 0xbb, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x02,
	0x3a, 0x70, 0x60, 0x9d, 0x00, 0x00, 0x00,
}
